ALTER TABLE rule_catalog
  ADD COLUMN catalog_entry_type VARCHAR(32) NOT NULL DEFAULT 'DISPLAY_RULE' AFTER version_status,
  ADD COLUMN display_rule_code VARCHAR(64) NULL AFTER catalog_entry_type,
  ADD COLUMN source_rule_ids JSON NULL AFTER display_rule_code;

UPDATE rule_catalog
SET catalog_entry_type = 'SOURCE_CLAUSE',
    display_rule_code = NULL
WHERE rule_id LIKE 'RG-%';

UPDATE rule_catalog
SET catalog_entry_type = 'DERIVATION'
WHERE rule_id IN (
  'RG-BASE-004', 'RG-BASE-005', 'RG-BASE-006', 'RG-BASE-010',
  'RG-TIME-001', 'RG-TIME-002', 'RG-TIME-003', 'RG-TIME-004', 'RG-TIME-005', 'RG-TIME-006',
  'RG-FDP-001', 'RG-FDP-002',
  'RG-EXT-003', 'RG-EXT-004', 'RG-EXT-009', 'RG-EXT-010',
  'RG-ULR-001', 'RG-ULR-002', 'RG-ULR-006',
  'RG-SPLIT-001', 'RG-SPLIT-002', 'RG-SPLIT-003', 'RG-SPLIT-007',
  'RG-LNP-001', 'RG-LNP-002', 'RG-LNP-005',
  'RG-MIX-001', 'RG-MIX-002', 'RG-MIX-004', 'RG-MIX-005',
  'RG-POS-001', 'RG-POS-004', 'RG-POS-005', 'RG-POS-006', 'RG-POS-007', 'RG-POS-008',
  'RG-STBY-003', 'RG-STBY-004', 'RG-STBY-005', 'RG-STBY-006', 'RG-STBY-007', 'RG-STBY-008',
  'RG-REST-001', 'RG-REST-002', 'RG-REST-005', 'RG-REST-006', 'RG-REST-007', 'RG-REST-011',
  'RG-REC-001', 'RG-REC-002', 'RG-REC-003',
  'RG-HOUR-008', 'RG-HOUR-009', 'RG-HOUR-010', 'RG-HOUR-011'
);

UPDATE rule_catalog
SET catalog_entry_type = 'SYSTEM_GATE',
    display_rule_code = rule_id
WHERE rule_id IN (
  'CREW_ASSIGNMENT_REQUIRED',
  'CREW_PAIR_REQUIRED',
  'CREW_REQUIRED_BASE_DATA',
  'CREW_STATUS_CONFLICT',
  'CREW_TIME_OVERLAP',
  'MANAGER_REVIEW_REQUIRED',
  'TASK_STATUS_BLOCKED'
);

UPDATE rule_catalog
SET catalog_entry_type = 'DERIVATION',
    display_rule_code = NULL
WHERE rule_id = 'FDP_STD_A';

INSERT INTO rule_catalog (
  rule_id, title_zh, title_en, rule_category, severity_default,
  source_section, source_clause, source_page, phase_code, active_flag,
  applicability, description_zh, description_en, trigger_summary_zh, trigger_summary_en,
  handling_method_zh, handling_method_en, exception_allowed, pdf_deeplink, version_status,
  catalog_entry_type, display_rule_code, source_rule_ids
) VALUES
  ('DR-BASE-DATA', '基础数据缺失', 'Required base data missing', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Base data readiness', 8, 'PHASE_3', TRUE,
   'Base data', '飞行员 home base、适应状态、机场时区等基础数据缺失时，不允许进入排班发布。', 'Blocks publish when home base, acclimatization, or airport timezone data is missing.',
   '排班、飞行、调机、休息等对象缺少必要基础字段。', 'Triggered when required base data is missing for crew or timeline events.',
   '补齐基础数据后重新校验。', 'Complete base data and rerun validation.', FALSE, '/docs/FOM-Chapter-7.pdf#page=8', 'PHASE_3',
   'DISPLAY_RULE', 'DR-BASE-DATA', JSON_ARRAY('RG-BASE-001', 'RG-BASE-002', 'RG-BASE-003')),
  ('DR-TIME-ORDER', '时间顺序错误', 'Invalid time order', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Time order', 8, 'PHASE_3', TRUE,
   'Time derivation', '任务或时间轴块结束时间不得早于开始时间。', 'Task and timeline block end time must be later than start time.',
   '任务、状态块或归档事实存在开始结束时间倒挂。', 'Triggered by invalid start/end order.',
   '修正时间事实后重新校验。', 'Fix time facts and rerun validation.', FALSE, '/docs/FOM-Chapter-7.pdf#page=8', 'ACTIVE',
   'DISPLAY_RULE', 'DR-TIME-ORDER', JSON_ARRAY('RG-TIME-008')),
  ('DR-FDP-LIMIT', 'FDP 超限', 'FDP limit exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'FDP Table A/B', 14, 'PHASE_3', TRUE,
   'FDP', '根据适应状态、start band、航段数和前序休息计算允许 FDP，计划或实际 FDP 超限时阻断。', 'Calculates allowable FDP from acclimatization, start band, sectors, and preceding rest.',
   '计划或实际 FDP 超过允许上限。', 'Triggered when planned or actual FDP exceeds the allowable limit.',
   '调整航班、增员、插入休息或进入例外流程。', 'Adjust flight, augment crew, insert rest, or start exception flow.', TRUE, '/docs/FOM-Chapter-7.pdf#page=14', 'PHASE_3',
   'DISPLAY_RULE', 'DR-FDP-LIMIT', JSON_ARRAY('RG-FDP-001', 'RG-FDP-002', 'RG-FDP-006')),
  ('DR-FDP-CALCULATION-DATA', 'FDP 计算数据缺失', 'FDP calculation data missing', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'FDP prerequisites', 14, 'PHASE_3', TRUE,
   'FDP', '缺航段数、start band 或 preceding rest band 时，不能计算 FDP，也不能发布。', 'Blocks publish when sector count, start band, or preceding rest band is missing.',
   'FDP 必要计算输入缺失。', 'Triggered by missing FDP calculation inputs.',
   '补齐航段、时区、报到或前序休息数据。', 'Complete sector, timezone, report, or preceding rest data.', FALSE, '/docs/FOM-Chapter-7.pdf#page=14', 'PHASE_3',
   'DISPLAY_RULE', 'DR-FDP-CALCULATION-DATA', JSON_ARRAY('RG-FDP-003', 'RG-FDP-004', 'RG-FDP-005')),
  ('DR-LONG-SECTOR-AUGMENTATION', '长航段未增员', 'Long sector missing augmentation', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Augmentation required', 14, 'PHASE_3', TRUE,
   'Augmentation', '两人制长航段或夜间长航段需要额外符合 relief 资格的飞行员。', 'Two-pilot long sectors require additional qualified relief crew.',
   '两人制 >9h，或夜间 >8h 但未配置额外机组。', 'Triggered by long two-pilot sectors without augmentation.',
   '增加 RELIEF / EXTRA 机组或调整航班。', 'Add RELIEF / EXTRA crew or adjust the flight.', FALSE, '/docs/FOM-Chapter-7.pdf#page=14', 'ACTIVE',
   'DISPLAY_RULE', 'DR-LONG-SECTOR-AUGMENTATION', JSON_ARRAY('RG-FDP-007', 'RG-EXT-011')),
  ('DR-REDUCED-REST-FDP', 'Reduced rest 后 FDP 限制', 'FDP after reduced rest restriction', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Reduced rest follow-up', 14, 'PHASE_3', TRUE,
   'FDP / Rest', '前序 rest 被减少后，后续 FDP 不能直接按普通表放行。', 'FDP after reduced rest cannot be released with the normal table only.',
   'Reduced rest 后又排普通 FDP 或 extended FDP。', 'Triggered when reduced rest is followed by restricted FDP patterns.',
   '进入特殊判断，补休或调整后续任务。', 'Use special handling, add rest, or adjust subsequent tasks.', TRUE, '/docs/FOM-Chapter-7.pdf#page=14', 'PHASE_3',
   'DISPLAY_RULE', 'DR-REDUCED-REST-FDP', JSON_ARRAY('RG-FDP-008', 'RG-REST-008')),
  ('DR-EXTENDED-FDP-ELIGIBILITY', 'Extended FDP 条件不满足', 'Extended FDP eligibility missing', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Extended FDP eligibility', 15, 'PHASE_3', TRUE,
   'Extended FDP', 'Extended FDP 必须同时满足 relief 资格、休息设施和最低 relief 时长。', 'Extended FDP requires relief qualification, facility, and minimum relief duration.',
   '缺 relief qualification、facility 或 relief 少于 3h。', 'Triggered by missing relief qualification/facility or relief under 3h.',
   '补齐增员、设施和 relief 事实，或取消 extended FDP。', 'Complete augmentation facts or remove extended FDP.', FALSE, '/docs/FOM-Chapter-7.pdf#page=15', 'PHASE_3',
   'DISPLAY_RULE', 'DR-EXTENDED-FDP-ELIGIBILITY', JSON_ARRAY('RG-EXT-001', 'RG-EXT-002')),
  ('DR-EXTENDED-FDP-LIMIT', 'Extended FDP 上限超限', 'Extended FDP limit exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Extended FDP limit', 15, 'PHASE_3', TRUE,
   'Extended FDP', '按 bunk/seat relief 公式计算延长值，超过总 FDP 上限时阻断。', 'Calculates bunk/seat extension and blocks over-limit extended FDP.',
   'Bunk / seat 延长后的 FDP 仍超过允许上限。', 'Triggered when extended FDP exceeds allowed bunk/seat limits.',
   '调整 relief、缩短 FDP 或重新安排航班。', 'Adjust relief, shorten FDP, or reschedule.', TRUE, '/docs/FOM-Chapter-7.pdf#page=15', 'PHASE_3',
   'DISPLAY_RULE', 'DR-EXTENDED-FDP-LIMIT', JSON_ARRAY('RG-EXT-003', 'RG-EXT-004')),
  ('DR-CONTROLS-LIMIT', '操纵时间超限', 'Controls time exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Controls limit', 15, 'PHASE_3', TRUE,
   'Extended FDP', '单人连续操纵和单 FDP 内累计操纵均有限制。', 'Controls duration is limited both continuously and cumulatively.',
   '连续 controls >8h 或累计 controls >10h。', 'Triggered by continuous controls over 8h or cumulative controls over 10h.',
   '重新安排 relief 和 controls 分配。', 'Rework relief and controls assignment.', FALSE, '/docs/FOM-Chapter-7.pdf#page=15', 'PHASE_3',
   'DISPLAY_RULE', 'DR-CONTROLS-LIMIT', JSON_ARRAY('RG-EXT-005', 'RG-EXT-006', 'RG-EXT-007')),
  ('DR-ULR-LIMIT', 'ULR 条件或上限不满足', 'ULR conditions or limits not met', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'ULR', 16, 'PHASE_3', TRUE,
   'ULR', 'ULR 需要按独立口径校验 pilots 数量、时差、FDP 上限、sector 和 bunk relief。', 'ULR is validated with independent pilot count, timezone, FDP, sector, and bunk relief rules.',
   'ULR 识别后任一上限或 relief 条件不满足。', 'Triggered when ULR limits or relief requirements fail.',
   '增加机组、调整 sectors、补 bunk relief 或改航班计划。', 'Augment crew, adjust sectors, add bunk relief, or change the flight plan.', FALSE, '/docs/FOM-Chapter-7.pdf#page=16', 'PHASE_3',
   'DISPLAY_RULE', 'DR-ULR-LIMIT', JSON_ARRAY('RG-ULR-001', 'RG-ULR-002', 'RG-ULR-003', 'RG-ULR-004', 'RG-ULR-005', 'RG-ULR-006', 'RG-ULR-007', 'RG-ULR-008')),
  ('DR-SPLIT-DUTY-LIMIT', 'Split duty 条件或上限不满足', 'Split duty conditions or limits not met', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Split duty', 17, 'PHASE_3', TRUE,
   'Split Duty', 'Split duty 需满足中间休息、前后段 FDP、总 FDP、住宿条件和不可叠加限制。', 'Split duty requires valid break, segment limits, total FDP limit, accommodation, and non-stacking restrictions.',
   'Split duty 任一条件不满足。', 'Triggered when any split-duty condition fails.',
   '补住宿条件、调整休息或取消 split duty 口径。', 'Add accommodation, adjust rest, or remove split-duty treatment.', TRUE, '/docs/FOM-Chapter-7.pdf#page=17', 'PHASE_3',
   'DISPLAY_RULE', 'DR-SPLIT-DUTY-LIMIT', JSON_ARRAY('RG-SPLIT-001', 'RG-SPLIT-002', 'RG-SPLIT-003', 'RG-SPLIT-004', 'RG-SPLIT-005', 'RG-SPLIT-006', 'RG-SPLIT-007', 'RG-SPLIT-008', 'RG-SPLIT-009', 'RG-SPLIT-010')),
  ('DR-LNP-LIMIT', 'Late night / overnight 超限', 'Late night / overnight limits exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Late night period', 18, 'PHASE_3', TRUE,
   'Late Night', '连续 LNP、6 天窗口、前置脱 duty、后续 free period 和 overnight 模式均需校验。', 'Validates consecutive LNP, six-day window, prior off-duty, subsequent free period, and overnight patterns.',
   'LNP duty 序列或 overnight 模式超限。', 'Triggered by LNP or overnight pattern violations.',
   '调整 duty 序列或补足 free period。', 'Adjust duty sequence or add free period.', TRUE, '/docs/FOM-Chapter-7.pdf#page=18', 'PHASE_3',
   'DISPLAY_RULE', 'DR-LNP-LIMIT', JSON_ARRAY('RG-LNP-001', 'RG-LNP-002', 'RG-LNP-003', 'RG-LNP-004', 'RG-LNP-005', 'RG-LNP-006', 'RG-LNP-007', 'RG-LNP-008')),
  ('DR-MIXED-DUTY-FDP', '混合 duty 影响 FDP', 'Mixed duty affects FDP', '告警留痕', 'ALERT',
   'PLAN / FRD 13', 'Mixed duty', 18, 'PHASE_3', TRUE,
   'Mixed Duty', 'Office duty、training、simulator 等混合任务会影响 FDP 起算、sector 和后续限制。', 'Office duty, training, and simulator duties affect FDP start, sectors, and limits.',
   '飞前公司任务、simulator 或 office duty 与飞行 duty 连续。', 'Triggered by mixed duty before or within flight duty.',
   '确认 duty 事实、岗位功能和 FDP 起算。', 'Confirm duty facts, role function, and FDP start.', TRUE, '/docs/FOM-Chapter-7.pdf#page=18', 'PHASE_3',
   'DISPLAY_RULE', 'DR-MIXED-DUTY-FDP', JSON_ARRAY('RG-MIX-001', 'RG-MIX-002', 'RG-MIX-003', 'RG-MIX-004', 'RG-MIX-005')),
  ('DR-POSITIONING-DUTY', 'Positioning duty 口径错误', 'Positioning duty treatment error', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Positioning duty', 19, 'PHASE_3', TRUE,
   'Positioning', 'Positioning 全额计 duty，默认不计 sector，但特殊场景会影响 split duty。', 'Positioning counts as duty and usually not as a sector, with split-duty exceptions.',
   'Positioning duty/sector 处理不符合规则。', 'Triggered when positioning duty/sector treatment is invalid.',
   '修正 positioning 类型、duty 计入和 sector 口径。', 'Fix positioning type, duty credit, and sector treatment.', TRUE, '/docs/FOM-Chapter-7.pdf#page=19', 'PHASE_3',
   'DISPLAY_RULE', 'DR-POSITIONING-DUTY', JSON_ARRAY('RG-POS-001', 'RG-POS-007', 'RG-POS-008', 'RG-POS-009')),
  ('DR-COMMUTE-FATIGUE', '通勤疲劳提醒', 'Commute fatigue reminder', '治理提醒', 'ALERT',
   'PLAN / FRD 13', 'Commute fatigue', 19, 'PHASE_3', TRUE,
   'Positioning', '正常通勤超过 90 分钟时给疲劳或住宿建议提醒。', 'Shows fatigue/accommodation reminder when normal commute exceeds 90 minutes.',
   '通勤时长超过提醒阈值。', 'Triggered by commute duration over threshold.',
   '提示住宿、疲劳风险或运行经理复核。', 'Suggest accommodation, fatigue review, or manager review.', TRUE, '/docs/FOM-Chapter-7.pdf#page=19', 'PHASE_3',
   'DISPLAY_RULE', 'DR-COMMUTE-FATIGUE', JSON_ARRAY('RG-POS-003')),
  ('DR-DELAYED-REPORT', '延误报到 FDP 口径', 'Delayed report FDP treatment', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Delayed report', 19, 'PHASE_3', TRUE,
   'Positioning / FDP', '改班延误会改变 allowable FDP 的 band 和起算点。', 'Delayed report changes allowable FDP band and start point.',
   '延误报到后未按更严格 band 或第 4 小时点计算。', 'Triggered by incorrect delayed-report FDP treatment.',
   '重算 report、FDP start 和 allowable FDP。', 'Recalculate report, FDP start, and allowable FDP.', TRUE, '/docs/FOM-Chapter-7.pdf#page=19', 'PHASE_3',
   'DISPLAY_RULE', 'DR-DELAYED-REPORT', JSON_ARRAY('RG-POS-004', 'RG-POS-005', 'RG-POS-006')),
  ('DR-STANDBY-DATA', 'Standby 数据缺失', 'Standby data missing', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Standby data', 19, 'PHASE_3', TRUE,
   'Standby', 'Standby 起止时间和性质必须明确。', 'Standby start, end, and type must be clear.',
   'Standby 缺起止时间或类型。', 'Triggered by missing standby time or type.',
   '补齐 standby 数据后重新校验。', 'Complete standby data and rerun validation.', FALSE, '/docs/FOM-Chapter-7.pdf#page=19', 'PHASE_3',
   'DISPLAY_RULE', 'DR-STANDBY-DATA', JSON_ARRAY('RG-STBY-001')),
  ('DR-STANDBY-LIMIT', 'Standby 超时', 'Standby limit exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Standby limit', 19, 'PHASE_3', TRUE,
   'Standby', 'Standby 最长 12 小时。', 'Standby must not exceed 12 hours.',
   'Standby block 超过 12h。', 'Triggered by standby duration over 12h.',
   '缩短或拆分 standby。', 'Shorten or split standby.', FALSE, '/docs/FOM-Chapter-7.pdf#page=19', 'ACTIVE',
   'DISPLAY_RULE', 'DR-STANDBY-LIMIT', JSON_ARRAY('RG-STBY-002')),
  ('DR-STANDBY-CALLOUT', 'Standby callout FDP / duty 计算错误', 'Standby callout FDP/duty calculation error', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Standby callout', 19, 'PHASE_3', TRUE,
   'Standby', 'Standby callout 后 FDP 和 duty 起算需按 standby 类型、report 和 post-flight 计算。', 'Standby callout FDP and duty are calculated from standby type, report, and post-flight duty.',
   'Standby callout 后 FDP/duty 口径错误。', 'Triggered by incorrect standby callout FDP/duty treatment.',
   '重算 standby 截止、FDP start 和总 duty。', 'Recalculate standby end, FDP start, and total duty.', TRUE, '/docs/FOM-Chapter-7.pdf#page=19', 'PHASE_3',
   'DISPLAY_RULE', 'DR-STANDBY-CALLOUT', JSON_ARRAY('RG-STBY-003', 'RG-STBY-004', 'RG-STBY-005', 'RG-STBY-006', 'RG-STBY-007', 'RG-STBY-008')),
  ('DR-MINIMUM-REST', '最低休息不足', 'Minimum rest insufficient', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Minimum rest', 20, 'PHASE_3', TRUE,
   'Rest', '前后 duty 间必须满足 minimum rest，含时差、住宿、standby callout 等口径。', 'Minimum rest between duties must satisfy timezone, accommodation, and standby-callout treatment.',
   '后续 duty 前 rest 少于要求值。', 'Triggered when rest before next duty is below requirement.',
   '插入 rest、调整 duty 或进入例外流程。', 'Insert rest, adjust duty, or start exception flow.', TRUE, '/docs/FOM-Chapter-7.pdf#page=20', 'PHASE_3',
   'DISPLAY_RULE', 'DR-MINIMUM-REST', JSON_ARRAY('RG-REST-001', 'RG-REST-002', 'RG-REST-003', 'RG-REST-005', 'RG-REST-006', 'RG-REST-007', 'RG-REST-011', 'RG-REST-012')),
  ('DR-REST-LOCAL-NIGHT', '休息缺 local night', 'Rest missing local night', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Local night rest', 20, 'PHASE_3', TRUE,
   'Rest', '前序 duty 超过 18 小时时，后续 rest 必须包含 local night。', 'Rest after duty over 18h must include a local night.',
   '长 duty 后 rest 缺 local night。', 'Triggered by missing local night after long duty.',
   '延长 rest 或调整后续 duty。', 'Extend rest or adjust subsequent duty.', TRUE, '/docs/FOM-Chapter-7.pdf#page=20', 'PHASE_3',
   'DISPLAY_RULE', 'DR-REST-LOCAL-NIGHT', JSON_ARRAY('RG-REST-004')),
  ('DR-DDO-VALIDITY', 'DDO 不满足', 'DDO requirement not met', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'DDO', 20, 'PHASE_3', TRUE,
   'DDO', '单次 DDO、14 天连续 DDO 和四周平均 DDO 均需满足。', 'Validates single DDO, rolling 14-day consecutive DDO, and four-week average DDO.',
   'DDO 时长、local nights、14 天或四周规则不满足。', 'Triggered by DDO duration, local-night, 14-day, or average violations.',
   '补 DDO、延长 DDO 或调整 duty 序列。', 'Add DDO, extend DDO, or adjust duty sequence.', TRUE, '/docs/FOM-Chapter-7.pdf#page=20', 'ACTIVE',
   'DISPLAY_RULE', 'DR-DDO-VALIDITY', JSON_ARRAY('RG-BASE-008', 'RG-DDO-001', 'RG-DDO-002', 'RG-DDO-003', 'RG-DDO-004')),
  ('DR-RECOVERY-REQUIRED', 'Recovery 不足', 'Recovery insufficient', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Recovery', 20, 'PHASE_3', TRUE,
   'Recovery', '跨时区 duty cycle 返 base 后，需按 Table X 和 reduction 限制满足 recovery。', 'After cross-timezone duty cycles, recovery must satisfy Table X and reduction limits.',
   'Recovery 缺失、过短或 reduction 超限。', 'Triggered by missing, insufficient, or over-reduced recovery.',
   '补 recovery / DDO 或调整后续飞行。', 'Add recovery / DDO or adjust subsequent flights.', TRUE, '/docs/FOM-Chapter-7.pdf#page=20', 'PHASE_3',
   'DISPLAY_RULE', 'DR-RECOVERY-REQUIRED', JSON_ARRAY('RG-BASE-007', 'RG-REC-001', 'RG-REC-002', 'RG-REC-003', 'RG-REC-004', 'RG-REC-005', 'RG-REC-006', 'RG-REC-007', 'RG-REC-008')),
  ('DR-CUMULATIVE-FLIGHT-HOURS', '累计飞行小时超限', 'Cumulative flight hours exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Flight hours', 21, 'PHASE_3', TRUE,
   'Cumulative Hours', '滚动 28 天和 12 个月飞行小时不得超过上限。', 'Rolling 28-day and 12-month flight hours must stay within limits.',
   '28 天或 12 个月累计飞行小时超限。', 'Triggered by cumulative flight-hour overrun.',
   '调整排班或触发经理复核。', 'Adjust roster or trigger manager review.', TRUE, '/docs/FOM-Chapter-7.pdf#page=21', 'PHASE_3',
   'DISPLAY_RULE', 'DR-CUMULATIVE-FLIGHT-HOURS', JSON_ARRAY('RG-HOUR-001', 'RG-HOUR-002')),
  ('DR-CUMULATIVE-DUTY-HOURS', '累计 duty 小时超限', 'Cumulative duty hours exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Duty hours', 21, 'PHASE_3', TRUE,
   'Cumulative Hours', '滚动 7 天、14 天、28 天 duty 小时及跨时区扣减需要满足。', 'Rolling 7-day, 14-day, 28-day duty hours and timezone reductions must be satisfied.',
   '累计 duty 小时超限或扣减口径错误。', 'Triggered by duty-hour overrun or invalid reduction treatment.',
   '调整 duty、positioning 或 standby 安排。', 'Adjust duty, positioning, or standby assignment.', TRUE, '/docs/FOM-Chapter-7.pdf#page=21', 'PHASE_3',
   'DISPLAY_RULE', 'DR-CUMULATIVE-DUTY-HOURS', JSON_ARRAY('RG-HOUR-003', 'RG-HOUR-004', 'RG-HOUR-005', 'RG-HOUR-006', 'RG-HOUR-007', 'RG-HOUR-008', 'RG-HOUR-009', 'RG-HOUR-010', 'RG-HOUR-011')),
  ('DR-RECORD-COMPLETENESS', '记录完整性缺失', 'Record completeness missing', '硬校验', 'BLOCK',
   'PLAN / FRD 13', 'Record completeness', 21, 'PHASE_3', TRUE,
   'Records / Archive', 'Duty、rest、岗位功能、飞行小时和归档事实缺失时，不得发布或归档。', 'Blocks publish/archive when duty, rest, role function, flight-hour, or archive facts are missing.',
   '关键记录缺失或不可追溯。', 'Triggered by missing or non-traceable records.',
   '补齐记录、归档表单或实际飞行小时。', 'Complete records, archive forms, or actual flight hours.', FALSE, '/docs/FOM-Chapter-7.pdf#page=21', 'PHASE_3',
   'DISPLAY_RULE', 'DR-RECORD-COMPLETENESS', JSON_ARRAY('RG-RECLOG-001', 'RG-RECLOG-003', 'RG-RECLOG-004')),
  ('DR-RECORD-RETENTION', '记录保留与复核提醒', 'Record retention and review reminder', '治理提醒', 'INFO',
   'PLAN / FRD 13', 'Record retention', 21, 'PHASE_3', TRUE,
   'Records / Archive', '运行记录、CDR 和 discretion sector 需要保留并进入月度复核。', 'Operational records, CDRs, and discretion sectors need retention and review.',
   '记录保留或月度复核要求触发。', 'Triggered by retention or review requirements.',
   '进入统计报表、归档报表或运行经理复核。', 'Show in reports or manager review.', TRUE, '/docs/FOM-Chapter-7.pdf#page=21', 'PHASE_3',
   'DISPLAY_RULE', 'DR-RECORD-RETENTION', JSON_ARRAY('RG-RECLOG-005', 'RG-RECLOG-006', 'RG-RECLOG-009')),
  ('DR-BLOCK-TIME-GOVERNANCE', 'Block time 偏差治理', 'Block time variance governance', '治理提醒', 'ALERT',
   'PLAN / FRD 13', 'Block time variance', 21, 'PHASE_3', TRUE,
   'Records / Archive', 'Block time 需要反映可实现运行时间，持续偏差应触发治理。', 'Block time must reflect achievable operation time and sustained variance triggers governance.',
   '计划 block time 持续偏离实际运行时间。', 'Triggered by sustained planned-versus-actual block-time variance.',
   '提示调整航班计划 block time。', 'Suggest adjusting planned block time.', TRUE, '/docs/FOM-Chapter-7.pdf#page=21', 'PHASE_3',
   'DISPLAY_RULE', 'DR-BLOCK-TIME-GOVERNANCE', JSON_ARRAY('RG-RECLOG-007', 'RG-RECLOG-008')),
  ('DR-DISCRETION-ELIGIBILITY', 'Discretion 使用条件不满足', 'Discretion eligibility not met', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Discretion eligibility', 23, 'PHASE_3', TRUE,
   'Discretion / CDR / AACM', 'Commander discretion 只能用于已开始 rostered FDP 后的不可预见情况，并需保留 PIC 决策。', 'Commander discretion applies only after started rostered FDP in unforeseeable circumstances with PIC decision record.',
   'Discretion 场景、授权、PIC 决策或预排逻辑不满足。', 'Triggered by invalid discretion context, authorization, PIC decision, or preplanning.',
   '取消 discretion、补授权和 PIC 决策记录。', 'Remove discretion or complete authorization and PIC decision records.', FALSE, '/docs/FOM-Chapter-7.pdf#page=23', 'PHASE_3',
   'DISPLAY_RULE', 'DR-DISCRETION-ELIGIBILITY', JSON_ARRAY('RG-DISC-001', 'RG-DISC-002', 'RG-DISC-003', 'RG-DISC-004', 'RG-DISC-005')),
  ('DR-DISCRETION-LIMIT', 'Discretion 延长/减休超限', 'Discretion extension or reduced rest exceeded', '硬校验', 'NON_COMPLIANT',
   'PLAN / FRD 13', 'Discretion limits', 23, 'PHASE_3', TRUE,
   'Discretion / CDR / AACM', 'Discretion 的 FDP 延长和 reduced rest 有明确上限和适用限制。', 'Discretion FDP extension and reduced rest have explicit limits and restrictions.',
   'FDP extension、reduced rest 或 room availability 超限。', 'Triggered by over-limit FDP extension, reduced rest, or insufficient room availability.',
   '改为 emergency 记录、补休或取消超限 discretion。', 'Record emergency, add rest, or remove over-limit discretion.', TRUE, '/docs/FOM-Chapter-7.pdf#page=23', 'PHASE_3',
   'DISPLAY_RULE', 'DR-DISCRETION-LIMIT', JSON_ARRAY('RG-DISC-006', 'RG-DISC-007', 'RG-DISC-008', 'RG-DISC-009')),
  ('DR-CDR-AACM-REPORTING', 'CDR / AACM 报送缺失', 'CDR / AACM reporting missing', '告警留痕', 'BLOCK',
   'PLAN / FRD 13', 'CDR / AACM', 23, 'PHASE_3', TRUE,
   'CDR / AACM', '每次 discretion 需生成 CDR；达到阈值时需在 7 天内向 AACM 报送。', 'Every discretion requires CDR, and threshold cases require AACM reporting within 7 days.',
   'CDR 缺失、公司请求缺书面记录或 AACM 报送未完成。', 'Triggered by missing CDR, missing company request record, or missing AACM report.',
   '补 CDR、公司请求记录或发起 AACM 报送。', 'Complete CDR, company request record, or AACM reporting.', FALSE, '/docs/FOM-Chapter-7.pdf#page=23', 'PHASE_3',
   'DISPLAY_RULE', 'DR-CDR-AACM-REPORTING', JSON_ARRAY('RG-DISC-010', 'RG-DISC-011', 'RG-DISC-012')),
  ('DR-SAFETY-CASE-AACM', '超长 FDP 安全论证 / AACM 提交', 'Safety case / AACM submission for very long FDP', '告警留痕', 'BLOCK',
   'PLAN.md', 'FDP over 18h safety case', 1, 'PHASE_3', TRUE,
   'AACM / Safety Case', '计划 FDP 超过 18 小时时，必须有 safety case 并提交 AACM。', 'Planned FDP over 18h requires safety case and AACM submission.',
   '计划 FDP 超过 18h。', 'Triggered by planned FDP over 18h.',
   '补 safety case 并进入 AACM 报送。', 'Complete safety case and AACM submission.', FALSE, '/docs/FOM-Chapter-7.pdf', 'PHASE_3',
   'DISPLAY_RULE', 'DR-SAFETY-CASE-AACM', JSON_ARRAY())
ON DUPLICATE KEY UPDATE
  title_zh = VALUES(title_zh),
  title_en = VALUES(title_en),
  rule_category = VALUES(rule_category),
  severity_default = VALUES(severity_default),
  source_section = VALUES(source_section),
  source_clause = VALUES(source_clause),
  source_page = VALUES(source_page),
  phase_code = VALUES(phase_code),
  active_flag = VALUES(active_flag),
  applicability = VALUES(applicability),
  description_zh = VALUES(description_zh),
  description_en = VALUES(description_en),
  trigger_summary_zh = VALUES(trigger_summary_zh),
  trigger_summary_en = VALUES(trigger_summary_en),
  handling_method_zh = VALUES(handling_method_zh),
  handling_method_en = VALUES(handling_method_en),
  exception_allowed = VALUES(exception_allowed),
  pdf_deeplink = VALUES(pdf_deeplink),
  version_status = VALUES(version_status),
  catalog_entry_type = VALUES(catalog_entry_type),
  display_rule_code = VALUES(display_rule_code),
  source_rule_ids = VALUES(source_rule_ids);
