CREATE TABLE IF NOT EXISTS user_preference (
  user_id BIGINT PRIMARY KEY,
  language_code VARCHAR(10) NOT NULL DEFAULT 'zh-CN',
  display_timezone_mode VARCHAR(20) NOT NULL DEFAULT 'UTC+8',
  date_format VARCHAR(30) NOT NULL DEFAULT 'YYYY-MM-DD',
  time_format VARCHAR(20) NOT NULL DEFAULT 'HH:mm',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_preference_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
